services:
  - type: worker
    name: olx-rent-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 