services:
  - type: web
    name: olx-rent-tracker
    env: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: node src/index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: false
      - key: SEARCH_CITY
        value: Suceava
      - key: SEARCH_MAX_PRICE
        value: 400
      - key: SEARCH_MIN_PRICE
        value: 200  
      - key: SEARCH_MIN_ROOMS
        value: 2
      - key: SEARCH_MAX_ROOMS
        value: 3
      - key: CHECK_INTERVAL
        value: 5
    plan: free
    # Chrome için gerekli bağımlılıklar
    buildFilter:
      paths:
        - package.json
        - src/**
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    packages:
      - chromium
      - chromium-browser
      - libx11-xcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxi6
      - libxtst6
      - libnss3
      - libcups2
      - libxss1
      - libxrandr2
      - libasound2
      - libatk1.0-0
      - libgtk-3-0
      - libgbm1 