name: Rent Tracker

on:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir çalışır
  workflow_dispatch:         # Manuel tetikleme için

jobs:
  track-rentals:
    runs-on: ubuntu-latest
    timeout-minutes: 10     # Maximum çalışma süresi
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Cache dependencies and sessions
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/puppeteer
            ./.wwebjs_auth
            ./.wwebjs_cache
          key: ${{ runner.os }}-deps-sessions-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-sessions-
            ${{ runner.os }}-
          
      - name: Install dependencies
        run: |
          npm install
          npm ls puppeteer
          
      - name: Get Chrome path
        id: chrome
        run: |
          CHROME_PATH=$(which chrome)
          echo "path=$CHROME_PATH" >> $GITHUB_OUTPUT
          echo "Found Chrome at: $CHROME_PATH"
          
      - name: Create data directory
        run: |
          mkdir -p data
          if [ ! -f data/seen-listings.json ]; then
            echo "[]" > data/seen-listings.json
          fi
          
      - name: Run tracker
        env:
          CHROME_PATH: ${{ steps.chrome.outputs.path }}
          DATA_DIR: ${{ github.workspace }}/data
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
        run: |
          echo "Chrome path: $CHROME_PATH"
          echo "Bot başlatılıyor..."
          node src/index.js
          
      - name: Commit changes
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f data/seen-listings.json
          git add -f .wwebjs_auth || true
          git add -f .wwebjs_cache || true
          git commit -m "Update seen listings and WhatsApp session [skip ci]" || echo "No changes to commit"
          git push 