name: Rent Tracker

on:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir çalışır
  workflow_dispatch:         # Manuel tetikleme için

jobs:
  track-rentals:
    runs-on: ubuntu-latest
    timeout-minutes: 10     # Maximum çalışma süresi
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/puppeteer
          key: ${{ runner.os }}-npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-deps-
            ${{ runner.os }}-
          
      - name: Install dependencies
        run: |
          npm install
          npm ls puppeteer
          
      - name: Get Chrome path
        id: chrome
        run: |
          CHROME_PATH=$(which chrome)
          echo "path=$CHROME_PATH" >> $GITHUB_OUTPUT
          echo "Found Chrome at: $CHROME_PATH"
          
      - name: Create data directory
        run: |
          mkdir -p data
          touch data/seen-listings.json
          echo "[]" > data/seen-listings.json
          
      - name: Run tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHROME_PATH: ${{ steps.chrome.outputs.path }}
          DATA_DIR: ${{ github.workspace }}/data
        run: |
          echo "Chrome path: $CHROME_PATH"
          echo "Bot başlatılıyor..."
          node src/index.js
          
      - name: Commit seen listings
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/seen-listings.json
          git commit -m "Update seen listings [skip ci]" || echo "No changes to commit"
          git push 