name: Rent Tracker

on:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir çalışır
  workflow_dispatch:         # Manuel tetikleme için

jobs:
  track-rentals:
    runs-on: ubuntu-latest
    timeout-minutes: 10     # Maximum çalışma süresi
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache/puppeteer
          key: ${{ runner.os }}-npm-puppeteer-firefox-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-puppeteer-firefox-
            ${{ runner.os }}-npm-puppeteer-
            ${{ runner.os }}-npm-
          
      - name: Install dependencies
        run: |
          npm install
          npm ls puppeteer
        
      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-esr
          
      - name: Run tracker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PUPPETEER_PRODUCT: firefox
          PUPPETEER_SKIP_DOWNLOAD: true
        run: |
          echo "Bot başlatılıyor..."
          node src/index.js
        continue-on-error: false 